[package]
name = "aoc2020"
version = "0.1.0"
authors = ["orhanbalci@gmail.com <orhanbalci@gmail.com>"]
edition = "2018"


[dependencies]
regex = "1.4.2"
lazy_static = "1.4.0"
anyhow="1.0.34"
thiserror="1.0.22"
bitvec = "0.19.4"