pub mod day01;
pub mod day02;
pub mod day03;
pub mod day04;
pub mod day05;
pub mod day06;
pub mod day07;
pub mod day08;

fn main() {
    let result_day01_part_i = day01::part_i();
    println!("Day 01 Part I  {}", result_day01_part_i);
    let result_day01_part_ii = day01::part_ii();
    println!("Day 01 Part II {}", result_day01_part_ii);
    let result_day02_part_i = day02::part_i();
    println!("Day 02 Part I  {}", result_day02_part_i);
    let result_day02_part_ii = day02::part_ii();
    println!("Day 02 Part II {}", result_day02_part_ii);
    let result_day03_part_i = day03::part_i();
    println!("Day 03 Part I  {}", result_day03_part_i);
    let result_day03_part_ii = day03::part_ii();
    println!("Day 03 Part II {}", result_day03_part_ii);
    let result_day04_part_i = day04::part_i();
    println!("Day 04 Part I  {}", result_day04_part_i);
    let result_day04_part_ii = day04::part_ii();
    println!("Day 04 Part II {}", result_day04_part_ii);
    let result_day05_part_i = day05::part_i();
    println!("Day 05 Part I  {}", result_day05_part_i);
    let result_day05_part_ii = day05::part_ii();
    println!("Day 05 Part II {}", result_day05_part_ii);
    let result_day06_part_i = day06::part_i();
    println!("Day 06 Part I  {}", result_day06_part_i);
    let result_day06_part_ii = day06::part_ii();
    println!("Day 06 Part II {}", result_day06_part_ii);
    let result_day07_part_i = day07::part_i();
    println!("Day 07 Part I {}", result_day07_part_i);
    let result_day07_part_ii = day07::part_ii();
    println!("Day 07 Part II {}", result_day07_part_ii);
    let result_day08_part_i = day08::part_i();
    println!("Day 08 Part I {:?}", result_day08_part_i);
    let result_day08_part_ii = day08::part_ii();
    println!("Day 08 Part II {:?}", result_day08_part_ii);
}
